# HTTP connector constants
DEFAULT_MAX_HTTP_RETRY_ATTEMPTS = 3
DEFAULT_RATE_LIMITER_JITTER_IN_SECONDS = 0.1
INITIAL_RETRY_BACKOFF_IN_SECONDS = 0.25
MIN_RETRY_JITTER_IN_SECONDS = 0.1
MAX_RETRY_JITTER_IN_SECONDS = 0.5

# REDIS constants
DEFAULT_LOCK_TIMEOUT_SEC = 5
DEFAULT_LOCK_BLOCKING_WAITING_TIMEOUT_SEC = 3
DEFAULT_EVENT_CACHE_TTL_SEC = 30
DEFAULT_JITTER_TTL_LOWER_LIMIT = 1
DEFAULT_JITTER_TTL_UPPER_LIMIT = 5
