# HTTP connector constants
DEFAULT_MAX_HTTP_RETRY_ATTEMPTS = 3
DEFAULT_RATE_LIMITER_JITTER_IN_SECONDS = 0.1
INITIAL_RETRY_BACKOFF_IN_SECONDS = 0.25
MIN_RETRY_JITTER_IN_SECONDS = 0.1
MAX_RETRY_JITTER_IN_SECONDS = 0.5
